# Ignore all testing data
# Ignore CSV files and Jupyter notebooks
exclude: testfiles/|\.(csv|ipynb)$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black
